# -*- coding: utf-8 -*-
"""function คำนวนพื้นที่ภายในห้าเหลี่ยม.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13n_5oBx4vP481OvdSKaKUFRucYNtptGW
"""

import math

def pentagon_area():
    side = 5
    root_5 = math.sqrt(5)
    area = (1/4) * math.sqrt(5 * (5 + 2*root_5)) * math.pow((5 - root_5), 2)
    return area

# ตัวอย่างการเรียกใช้ฟังก์ชัน
print("พื้นที่ของห้าเหลี่ยมคือ: ", pentagon_area())