# -*- coding: utf-8 -*-
"""สำเนาของ Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N8vyATt_ohYbrTCn0bqPlRmRKcJSAAgZ
"""

def calculate_oxygen_amount(volume):
    # แปลงจำนวนน้ำเป็นกรัม
    water_amount = volume * 1000
    # คำนวณเวลาที่ใช้ในการแยกโดยแปลงเป็นวินาที
    time = 143 * volume
    # จำนวนไอน้ำที่เกิดขึ้นต่อวินาที
    steam_rate = 167 / 1000
    # จำนวนน้ำที่กลับเป็นเหลืองควบแน่นต่อวินาที
    water_rate = 89 / 1000
    # จำนวนออกซิเจนที่ได้จากการแยกในช่วงเวลา time วินาที
    oxygen_amount = (888 / 1000) * time
    # คำนวณจำนวนน้ำเสียที่เหลือหลังจากแยกออกเป็นไอน้ำและออกซิเจน
    remaining_water = water_amount - (water_rate + steam_rate) * time
    # คำนวณจำนวนออกซิเจนที่เป็นไปได้จากน้ำเสียที่เหลือ
    oxygen_from_remaining_water = remaining_water * 0.44
    # รวมจำนวนออกซิเจนทั้งหมด
    total_oxygen = oxygen_amount + oxygen_from_remaining_water
    # แปลงหน่วยเป็นกิโลกรัม
    total_oxygen_kg = total_oxygen / 1000
    return total_oxygen_kg


polluted_water_volume = float(input("ป้อนปริมาณน้ำเสีย (ลิตร): "))
oxygen_amount = calculate_oxygen_amount(polluted_water_volume)
print("มวลออกซิเจนที่ได้จากการแยกน้ำเสีย: {:.2f} กิโลกรัม".format(oxygen_amount))