# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QLrNiEh5wzeJeLMKIdfcLKIMmK71sUJ7
"""

height = float(input("ป้อนตัวเลขความสูงของสี่เหลี่ยมคางหมู : "))
side = float(input("ป้อนผลบวกของด้านคู่ขนานของสี่เหลี่ยมคางหมู : "))
area = (1/2) * height * side
 
print("พื้นที่สี่เหลี่ยมคางหมู คือ ", area)