# -*- coding: utf-8 -*-
"""สร้าง function คำนวนพื้นที่ภายในสี่เหลี่ยมข้าวหลามตัด ขึ้นมาใช้เอง.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEMd4xygbbhOAyHepAO-dhFZOQGCs3Du
"""

Area = (a + b) * h / 2
def trapezoid_area(a, b, h):
    area = (a + b) * h / 2
    return area
    # คำนวณพื้นที่สี่เหลี่ยมข้าวหลามตัด
a = 10
b = 6
h = 4
area = trapezoid_area(a, b, h)
print("พื้นที่สี่เหลี่ยมข้าวหลามตัด =", area)